"use client";
import { CircleCheck, CircleX, Clock, Database, Sparkles } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import type { Conversation } from "@/lib/types";
import { formatDateTime, titleCase } from "@/lib/utils";
import { evaluationMeta, formatValue } from "./helpers";
import { InsightsPanel } from "./InsightsPanel";

function SectionTitle({ children, right }: { children: React.ReactNode; right?: React.ReactNode }) {
  return (
    <div className="mb-2.5 flex items-center justify-between gap-3">
      <h4 className="text-[11px] font-medium uppercase tracking-[0.08em] text-muted-foreground">{children}</h4>
      {right}
    </div>
  );
}

export function SummaryPanel({ c }: { c: Conversation }) {
  const data = Object.entries(c.dataCollection ?? {});
  const evals = Object.entries(c.evaluation ?? {});
  const zoho = c.zohoSync;
  const outcomeBadge =
    c.callSuccessful === "success" ? (
      <Badge variant="success">
        <CircleCheck /> Call successful
      </Badge>
    ) : c.callSuccessful === "failure" ? (
      <Badge variant="destructive">
        <CircleX /> Call unsuccessful
      </Badge>
    ) : (
      <Badge variant="secondary">Outcome unknown</Badge>
    );

  return (
    <div className="space-y-7">
      <InsightsPanel c={c} />

      <section>
        <SectionTitle right={outcomeBadge}>Summary</SectionTitle>
        {c.summaryTitle ? <p className="mb-1 font-medium">{c.summaryTitle}</p> : null}
        {c.summary ? <p className="text-[14px] leading-relaxed text-foreground/90">{c.summary}</p> : <p className="text-sm italic text-muted-foreground">No summary yet — it is generated by ElevenLabs after the call ends.</p>}
      </section>

      <section>
        <SectionTitle>Data collection</SectionTitle>
        {data.length ? (
          <div className="overflow-hidden rounded-lg border border-border">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead className="w-[38%]">Field</TableHead>
                  <TableHead>Value</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {data.map(([key, entry]) => (
                  <TableRow key={key}>
                    <TableCell className="align-top font-mono text-[12.5px]">{key}</TableCell>
                    <TableCell className="align-top">
                      <div className="break-words text-[13.5px]">{formatValue(entry?.value)}</div>
                      {entry?.rationale ? <div className="mt-0.5 text-xs leading-relaxed text-muted-foreground">{entry.rationale}</div> : null}
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </div>
        ) : (
          <p className="text-sm text-muted-foreground">No data collected. Add data-collection fields on the agent to extract structured answers from calls.</p>
        )}
      </section>

      <section>
        <SectionTitle>Evaluation</SectionTitle>
        {evals.length ? (
          <ul className="divide-y divide-border rounded-lg border border-border">
            {evals.map(([name, ev]) => (
              <li key={name} className="flex items-start gap-3 px-3 py-2.5">
                <Sparkles className="mt-0.5 size-4 shrink-0 text-primary" strokeWidth={1.8} />
                <div className="min-w-0 flex-1">
                  <div className="flex items-center justify-between gap-3">
                    <span className="truncate text-[13.5px] font-medium">{titleCase(name)}</span>
                    <Badge variant={evaluationMeta(ev?.result)}>{titleCase(ev?.result) || "—"}</Badge>
                  </div>
                  {ev?.rationale ? <p className="mt-0.5 text-xs leading-relaxed text-muted-foreground">{ev.rationale}</p> : null}
                </div>
              </li>
            ))}
          </ul>
        ) : (
          <p className="text-sm text-muted-foreground">No evaluation criteria ran for this call.</p>
        )}
      </section>

      <section>
        <SectionTitle>Zoho sync</SectionTitle>
        <div className="rounded-lg border border-border p-3.5">
          {!zoho || (!zoho.attemptedAt && !zoho.pushedAt && !zoho.error) ? (
            <div className="flex items-start gap-2.5 text-sm text-muted-foreground">
              <Database className="mt-0.5 size-4 shrink-0" strokeWidth={1.8} />
              <span>Not pushed to Zoho. Attach a voice agent to My Leads with “Push to Zoho” enabled to sync collected data automatically.</span>
            </div>
          ) : (
            <div className="space-y-3">
              {zoho.pushedAt ? (
                <div className="flex items-center gap-2 text-sm text-success">
                  <CircleCheck className="size-4" /> Pushed to Zoho · {formatDateTime(zoho.pushedAt)}
                </div>
              ) : zoho.error ? (
                <div className="flex items-start gap-2 text-sm text-destructive">
                  <CircleX className="mt-0.5 size-4 shrink-0" />
                  <span>
                    Push failed{zoho.attemptedAt ? ` · ${formatDateTime(zoho.attemptedAt)}` : ""}: {zoho.error}
                  </span>
                </div>
              ) : (
                <div className="flex items-center gap-2 text-sm text-muted-foreground">
                  <Clock className="size-4" /> Attempted {formatDateTime(zoho.attemptedAt)} — nothing to update
                </div>
              )}
              {zoho.updatedFields?.length ? (
                <div>
                  <div className="mb-1.5 text-xs text-muted-foreground">Updated fields</div>
                  <div className="flex flex-wrap gap-1">
                    {zoho.updatedFields.map((f) => (
                      <Badge key={f} variant="soft" className="font-mono">
                        {f}
                      </Badge>
                    ))}
                  </div>
                </div>
              ) : null}
              {zoho.skippedFields?.length ? (
                <div>
                  <div className="mb-1.5 text-xs text-muted-foreground">Skipped (already filled or empty)</div>
                  <div className="flex flex-wrap gap-1">
                    {zoho.skippedFields.map((f) => (
                      <span key={f} className="rounded-full border border-border px-2 py-0.5 font-mono text-[11px] text-muted-foreground">
                        {f}
                      </span>
                    ))}
                  </div>
                </div>
              ) : null}
            </div>
          )}
        </div>
      </section>
    </div>
  );
}
